# Generated by Django 2.2.2 on 2021-08-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уровня доступа')),
                ('level', models.IntegerField(verbose_name='Число уровня доступа(Доступ будет разрешен в том случае, если у человека это число уровеня доступа или выше)')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Отчество')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='media/visitors_faces/', verbose_name='Фотография лица')),
                ('face_image_vectors', models.TextField(null=True)),
                ('access_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='FaceAuth.AccessLevel')),
            ],
        ),
    ]
