# Generated by Django 2.2.2 on 2021-08-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='FaceAuth/media/visitors_faces/', verbose_name='Фотография лица'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='face_image_vectors',
            field=models.BinaryField(null=True),
        ),
    ]
