# Generated by Django 2.2.2 on 2021-08-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0002_auto_20210825_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название камеры')),
                ('api_key', models.CharField(max_length=32, verbose_name='API ключ')),
            ],
        ),
    ]
