# Generated by Django 2.2.2 on 2021-08-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0003_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='need_access_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='FaceAuth.AccessLevel', verbose_name='Уровень доступа необходимый для взаимодействия'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='access_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='FaceAuth.AccessLevel', verbose_name='Уровень доступа пользователя'),
        ),
    ]
