# Generated by Django 2.2.2 on 2021-08-25 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0004_auto_20210825_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslevel',
            options={'verbose_name': 'Уровень доступа', 'verbose_name_plural': 'Уровни доступа'},
        ),
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Посетитель', 'verbose_name_plural': 'Поситетели'},
        ),
        migrations.CreateModel(
            name='CameraLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(verbose_name='Успешно?')),
                ('image', models.ImageField(upload_to='FaceAuth/media/log_faces/', verbose_name='Изображение из запроса')),
                ('date', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='FaceAuth.Camera', verbose_name='Камера')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
