# Generated by Django 2.2.2 on 2021-08-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0005_auto_20210825_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameralog',
            name='image',
        ),
    ]
