# Generated by Django 2.2.2 on 2021-08-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FaceAuth', '0006_remove_cameralog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralog',
            name='image',
            field=models.ImageField(default=1, upload_to='FaceAuth/media/log_faces/', verbose_name='Изображение из запроса'),
            preserve_default=False,
        ),
    ]
